Repository AY2122S1-CS2113T-F11-4/tp, pull requests merged in 2021-11, with the labels that each got.

#210 Search command
  src/main/java/seedu/duke/command/SearchCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Wrapping.java
Labels: type.Feature

#214 Junfeng's PPP draft
  docs/AboutUs.md
  docs/team/yuejunfeng0909.md
Labels: type.Documentation

#229 bug fix
  src/main/java/seedu/duke/model/Shelf.java
  src/main/java/seedu/duke/model/ShelfList.java
  src/main/java/seedu/duke/model/exception/DuplicateShelfException.java
Labels: type.Bug

#224 update architecture diagram
  docs/DeveloperGuide.md
  docs/puml/Architecture.puml
Labels: type.Documentation

#234 Documentation improve format
  docs/DeveloperGuide.md
  docs/diagrams/GeneralProgramFlowSequenceDiagram.png
  docs/diagrams/GeneralProgramFlowSequenceDiagram.svg
  docs/diagrams/ListCommandSequenceDiagram.svg
  docs/diagrams/Model_addShelf.svg
  docs/diagrams/Model_newShelf.svg
  docs/diagrams/Storage_loadData.svg
  docs/diagrams/Storage_saveData.svg
Labels: type.Documentation

#235 fix wrong diagram path
  docs/DeveloperGuide.md
  docs/diagrams/Architecture.svg
Labels: type.Documentation

#238 Update model class diagram
  docs/DeveloperGuide.md
  docs/diagrams/Model_ClassDiagram.svg
  docs/diagrams/Model_ObjectDiagram.svg
  docs/puml/Model_ClassDiagram.puml
  docs/puml/Model_ObjectDiagram.puml
  docs/puml/Style.puml
Labels: type.Documentation

#239 Minor updates to DG for storage component
  docs/DeveloperGuide.md
Labels: type.Documentation

#240 Update UI diagrams, rename some diagrams
  docs/DeveloperGuide.md
  docs/diagrams/Architecture_GeneralProgramFlowSequenceDiagram.svg
  docs/diagrams/GeneralProgramFlowSequenceDiagram.svg
  docs/diagrams/Model_ClassDiagram.svg
  docs/diagrams/UI_ClassDiagram.svg
  docs/diagrams/seedu_duke_ui.svg
  docs/puml/Architecture_GeneralProgramFlowSequenceDiagram.puml
  docs/puml/GeneralProgramFlowSequenceDiagram.puml
  docs/puml/Model_ClassDiagram.puml
  docs/puml/UI_ClassDiagram.puml
  src/main/java/seedu/duke/CliverShelf.java
  src/main/java/seedu/duke/logic/parser/exception/IllegalFormatException.java
  src/main/java/seedu/duke/ui/PredefinedMessages.java
  src/test/java/seedu/duke/ui/CliverShelfPredefinedMessagesTest.java
Labels: type.Documentation

#241 fix issue addressed by TA
  docs/DeveloperGuide.md
  docs/diagrams/ParserClassDiagram.png
  docs/diagrams/seedu_duke_logic.drawio.svg
Labels: type.Documentation

#223 UGDG help command for Search
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/logic/command/HelpCommand.java
Labels: type.Documentation

#250 Replace "CliverShelf" with "CLIverShelf" in documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/Logic_ClassDiagram.svg
  docs/puml/Logic_ClassDiagram.puml
  docs/team/zh1huang.md
Labels: type.Documentation

#261 Junfeng ppp
  docs/UserGuide.md
  docs/team/yuejunfeng0909.md
Labels: type.Documentation

#264 Update DG UI component
  docs/DeveloperGuide.md
  docs/diagrams/UI_StaticPrintMessageSequenceDiagram.svg
  docs/puml/UI_StaticPrintMessageSequenceDiagram.puml
  src/main/java/seedu/duke/ui/MessageBubble.java
Labels: type.Documentation

#262 Update DG diagrams
  docs/diagrams/ListCommandSequenceDiagram.svg
  docs/diagrams/Logic_ClassDiagram.svg
  docs/puml/Logic_ClassDiagram.puml
  docs/puml/Logic_ListCommandSequenceDiagram.puml
  docs/team/zh1huang.md
Labels: type.Documentation

#280 Update Junfeng's PPP
  docs/team/yuejunfeng0909.md
Labels: type.Documentation

#281 Add on to DG Intro, improve PPP
  docs/DeveloperGuide.md
  docs/team/haoyusimon.md
Labels: type.Documentation

#284 PPP update
  docs/team/zh1huang.md
Labels: type.Documentation

#285 Formatting
  docs/DeveloperGuide.md
Labels: type.Documentation

#286 Hide sold item from search result
  src/main/java/seedu/duke/logic/command/SearchCommand.java
Labels: type.Bug
