Repository AY2122S1-CS2113T-F11-4/tp, pull requests merged in 2021-10, with the labels that each got.

#8 #6 Create user guide
  docs/README.md
  docs/UserGuide.md
Labels: type.Documentation

#24 Basic data structure
  src/main/java/seedu/duke/model/ContainerList.java
  src/main/java/seedu/duke/model/Item.java
  src/main/java/seedu/duke/model/ItemContainer.java
  src/main/java/seedu/duke/model/exception/InvalidFormat.java
Labels: priority.High

#36 Add logging for seedu/duke/model
  src/main/java/seedu/duke/model/Item.java
  src/main/java/seedu/duke/model/ItemContainer.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/EditCommandTest.java
  src/test/java/seedu/duke/model/ItemTest.java
Labels: priority.Medium

#37 Add Assertion and Logging
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
Labels: priority.Medium

#119 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/seedu_duke_model.drawio.svg
  docs/diagrams/seedu_duke_model_newshelf.drawio.svg
  src/main/java/seedu/duke/model/ShelfList.java
Labels: type.Documentation
